sanity-io/next-sanity

README.md
The example was using createCurrentUserHook() but hadn't imported it.
=> Imports missing dependency

src/types.ts
The types for the client doesn't include the withCredentials property that picosanity defines at https://github.com/rexxars/picosanity/blob/main/client.d.ts#L9
=> Add missing withCredentials to picosanity type

CHANGELOG.md, package.json, src/client.ts, src/index.ts, src/types.ts
Published a beta of this PR, you can test it using `npm i next-sanity@beta`.
=> fix: re-export `@sanity/client` types

README.md
Clean up minor grammar mistakes in
the README to improve clarity.
Add a relative link to the LICENSE file
for ease of access.
=> docs(readme): fix grammar mistakes

package-lock.json, package.json
Next v13 was released today, and things seems to work fine, so we should expand the version range to allow for it.
=> fix: expand supported next version range to allow v13

src/types.ts, src/useSubscription.ts
The SubscriptionOptions interface not being exported causes an error with Typescript.
Here's a link to a github issue describing the issue: 
https://github.com/microsoft/TypeScript/issues/5711
I moved the types to the ./types.ts file which has all of it's types exported from index.ts
=> fix: export the subscription options to avoid ts errors

.releaserc.json, CHANGELOG.md, README.md, package-lock.json, package.json, src/useSubscription.ts
Exposes the `allowTypes` option that's introduced in a prerelease of `@sanity/groq-store`: https://github.com/sanity-io/groq-store/pull/2
Install it using `npm i --save-exact next-sanity@add-type-allowlist`.
And in `createPreviewSubscriptionHook` you can now set the `allowTypes` option:
```tsx
import {createPreviewSubscriptionHook} from 'next-sanity'
const useQuerySubscription = createPreviewSubscriptionHook({
/* ... */
allowTypes: ['post', 'author', 'sanity.imageAsset'],
})
```
To quickly list types in a dataset run this groq query in `@sanity/vision`, with the `apiVersion` set to `vX`:
```groq
array::unique(*._type)
```
=> feat: add support for fetching subset of dataset by type

package.json
This changes the peer dependency versions to use explicit latest major versions.
With the exception of `styled-components` which is a `^5.2` peer dependency of the `sanity` package.
=> fix(deps): correct peer dependency versions

README.md
Add a README section about what peer dependencies must be installed when using `next-sanity/studio` features.
=> docs: add peer deps installation section

README.md
Not sure if this is acceptable since the README doesn't mention any process for additions, but please let me know if that section isn't meant to include more starters.
This PR adds the [commercelayer-sanity-template](https://github.com/commercelayer/commercelayer-sanity-template) that now supports Sanity studio v3 and `next-sanity`.
=> docs: add new starter

README.md
This pull request removes the experimental text for the next.js app dir from the readme file. With the release of Next.js 13.4, the next/app directory is now considered stable, so there is no longer a need for this experimental text.
=> Removed "Experimental" Text for the next.js app dir

README.md
Removed the disclaimer which states `We support the new appDir mode in Next, [but please note that appDir shouldn't be used in production before Vercel says it's stable](https://beta.nextjs.org/docs/getting-started).`
=> Remove Disclaimer for 'appDir' in README

README.md
This PR cleans up the README a bit, adds more examples, gives examples more context, makes links easier to manage, and fixes some misses and inconsistencies in the examples. 
Before merging, I need review on:
There are certainly more improvements we can add, but this is at least a good start.
=> fix: give README a content hug

README.md
The example for the client.ts file is missing the export for the client.
=> docs: add missing export in client.ts example

.gitignore, README.md
Updated the code sample for time based revalidation docs to be passed a second argument as an object with the next property inside it. Previously it was shown to be passing the next property directly, which was an error.
=> docs: next revalidate should be inside an object

README.md
The `await` is not needed for `revalidateTag` and the route this would need to be on is `/src/app/api/revalidate/route.ts`
=> fix(docs): update revalidate app dir snippet

app/studio/[[...tool]]/page.tsx, package.json, src/studio/metadata.ts, src/studio/viewport.ts
With Next.js 14 the `viewport` property has been removed from the metadata API and should now be exported as a separate object: https://nextjs.org/docs/app/api-reference/functions/generate-viewport
This adds a default `viewport` object that can be used just like the existing `metadata` object.
This is a breaking change since it removes the `viewport` property from the `metadata` export. Next will [set defaults for width and initialScale](https://nextjs.org/docs/app/api-reference/functions/generate-viewport#width-initialscale-and-maximumscale) but this still means that a project running Next 13.x would loose the `viewport-fit` configuration when updating to this change.
Not sure how you want to handle backwards compatibility here; I'm open to make changes as needed to this PR. 😊
=> feat!: add support for Next.js 14 viewport object

package.json
In #718, I forgot to add the new viewport file to `typesVersions` which means next-sanity 6.0.0 doesn't build properly when using TypeScript atm:
=> fix: add missing viewport type to package.json

package-lock.json, package.json
Relates to #942. In v4.0.1 of `@sanity/webhook` it started specifying node v20 as its recommended engine. [This is due to Node not shipping Web Crypto in v18.](https://github.com/sanity-io/webhook-toolkit/issues/44) Next.js gets around this by polyfilling these APIs so that they're available, both in the Node and Edge runtimes.
v4.0.1 is otherwise identical to v4.0.0 so the best course of action is to downgrade to 4.0.0 for now. By the time we make changes to `@sanity/webhook` we'll likely have Node v20 be the LTS.
=> fix(deps): downgrade webhooks package to solve engines warning

app/PreviewProvider.tsx, app/layout.tsx, app/studio/[[...tool]]/Studio.tsx, package-lock.json, package.config.ts, package.json, src/index.ts, src/visual-editing/VisualEditing.tsx, src/visual-editing/index.tsx
Usage:
```tsx
import {draftMode} from 'next/headers'
import {VisualEditing} from 'next-sanity'
export default function RootLayout({children}: {children: React.ReactNode}) {
return (
<html lang="en">
<head />
<body>
{children}
{draftMode().isEnabled && <VisualEditing />}
</body>
</html>
)
}
```
=> feat: add `<VisualEditing />` component

README.md
Adds `params` parameter to fix the example of `Time-based revalidation` in Next.js
`client.fetch` function API looks like this:
```
/**
* Perform a GROQ-query against the configured dataset.
*
* @param query - GROQ-query to perform
* @param params - Optional query parameters
* @param options - Optional request options
*/
fetch<R = Any, Q extends QueryWithoutParams | QueryParams = QueryParams>(
query: string,
params: Q extends QueryWithoutParams ? QueryWithoutParams : Q,
options?: FilteredResponseQueryOptions,
): Promise<R>
```
Yet, in the current example `options` parameter is passed as a second argument to `client.fetch` function which is not correct
```
const home = await client.fetch<HomePageProps>(`*[_id == "home"][0]{...,navItems[]->}`,
{next: {
revalidate: 3600 // look for updates …
```
=> docs: fix time-based revalidation rsc example

packages/next-sanity/MIGRATE-v8-to-v9.md, packages/next-sanity/package.json, pnpm-lock.yaml
As v2.0.11 is now passing publint and ready for turbopack it's time to bump the req
=> fix!: require `@sanity/ui` `2.0.11` or later

packages/next-sanity/README.md
`deskTool` is deprecated now and it's recommended to use `structureTool` now.
=> docs(README): replace deskTool with structureTool

apps/mvp/app/sanity.client.ts, apps/mvp/next.config.mjs, apps/mvp/sanity.config.ts, packages/next-sanity/src/visual-editing/client-component/index.ts, packages/next-sanity/src/visual-editing/client-component/utils.ts, packages/next-sanity/src/visual-editing/index.tsx, turbo.json
Adds `basePath` support to `<VisualEditing />` to integrate with https://nextjs.org/docs/app/api-reference/next-config-js/basePath
The default value is detected by reading the same env variable that next.js reads internally. Since it's an internal env variable it'll console.warn telling you to add the prop manually to ensure it'll keep working should next.js change in the future:
```bash
Detected next basePath as "/e2e" by reading "process.env.__NEXT_ROUTER_BASEPATH". If this is incorrect then you can set it manually with the basePath prop on the <VisualEditing /> component.
```
When using `basePath` with Presentation Tool it's important that the prefix must be added on these touch points, assuming `next.config.ts` sets `basePath: '/docs'` and that the studio is mounted on …
=> feat(visual-editing): add `basePath` support

apps/mvp/next.config.mjs, apps/mvp/package.json, apps/static/package.json, package.json, packages/next-sanity/package.json, pnpm-lock.yaml
Closes #1515.
Also bumps the v18 req to v18.3 as it has all the deprecation warnings needed to know if the userland codebase is ready for v19 yet: https://github.com/facebook/react/blob/main/CHANGELOG.md
Also sets up e2e tests to test on v19 since next v15 will be dropping support for v18, and this library will follow suit and also drop v18 in a new major.
And lastly, it tests the new React Compiler ✨
=> fix: add v19 to `react` peer dep range

packages/next-sanity/src/image/imageLoader.ts
The default value for the fit param should be set to max to support the vertical images out of the box.
=> Set fit param to max on the image loader

apps/mvp/next.config.mjs, apps/mvp/sanity.config.ts, packages/next-sanity/src/visual-editing/client-component/index.ts, packages/next-sanity/src/visual-editing/client-component/utils.ts, packages/next-sanity/src/visual-editing/index.tsx
Like #1510 this PR adds `trailingSlash` support to `<VisualEditing />` to integrate with https://nextjs.org/docs/pages/api-reference/next-config-js/trailingSlash
The default value is detected by reading the same env variable that next.js reads internally. Since it's an internal env variable it'll console.warn telling you to add the prop manually to ensure it'll keep working should next.js change in the future:
```bash
Detected next trailingSlash as true by reading "process.env.__NEXT_TRAILING_SLASH". If this is incorrect then you can set it manually with the trailingSlash prop on the <VisualEditing /> component.
```
When using `trailingSlash` with Presentation Tool it's important that the suffix must be added on these touch points, assuming `next.config.ts` sets `basePath: '/docs'` and …
=> feat(visual-editing): add `trailingSlash ` support

packages/next-sanity/package.json
We'll come back with a different implementation once the React Compiler WG has made a decision on the preferred mechanism
=> fix: remove react-compiler export condition

packages/next-sanity/README.md
* The second param in this function actually stops it from working
* Also removed `server-only` because this version of the client file doesn't include any tokens
=> fix: revalidatePath function

packages/next-sanity/src/visual-editing/client-component/VisualEditing.tsx
Adds support for the new `components` prop used for mounting custom components in the `<VisualEditing>` component.
=> chore: pass components prop to visual editing component

packages/next-sanity/src/visual-editing/client-component/VisualEditing.tsx
Adds support for the new `components` prop used for mounting custom components in the `<VisualEditing>` component.
=> feat: pass components prop to visual editing component

packages/next-sanity/package.config.ts, packages/next-sanity/package.json, packages/next-sanity/src/index.edge-light.ts, packages/next-sanity/src/visual-editing/client-component/VisualEditingLazy.tsx, packages/next-sanity/src/visual-editing/client-component/index.ts, packages/next-sanity/src/visual-editing/index.tsx
=> fix: edge runtime dynamic code eval

packages/next-sanity/README.md
Moving the docs to be more in line with the rest of the formatting.
* Fixed the navigation at the top to reflect the live content API.
* Moved the live content API docs from being at the top to being in line with other features and not blocking initial set-up docs from being the priority.
=> docs: reformat live content api docs

packages/next-sanity/src/draft-mode/define-enable-draft-mode.ts
Small change to follow the same conventions for setting the preview/draft cookie as with other frameworks we support.
Safari seems to have issues with setting secure cookies over http within an iframe, or at least some subset of that combination.
Seems to do the trick on the Vercel deployment over https too.
=> fix: ensure draft mode cookies are set on safari

packages/next-sanity/README.md
=> fix(docs): add `use client` directives to `sanity.config.ts` snippets

packages/next-sanity/src/image/imageLoader.ts, packages/next-sanity/test/imageLoader.test.ts
Noticed that the `imageLoader` fn overrides the `fit` param, even tho the code looks like it should only override it when not set. I had some issues with the `hotspot` not being set correctly, so I fixed this and copied the loader to my codebase. Perhaps someone else runs into the same issue. Also, added tests for `imageLoader`.
=> imageLoader: do not overwrite existing fit param

packages/next-sanity/PREVIEW-app-router.md, packages/next-sanity/PREVIEW-pages-router.md, packages/next-sanity/README.md
Since https://github.com/sanity-io/client/pull/1007 the client warns when using `perspective: 'previewDrafts'`. This PR refactors to the new `perspective: 'drafts'` approach.
=> fix(docs): replace `previewDrafts` with `drafts`

packages/next-sanity/package.json
[Since next v15.1 react 19 has been stable](https://nextjs.org/blog/next-15-1).
=> fix!: drop next v14 and react 18

packages/next-sanity/EXPERIMENTAL-CACHE-COMPONENTS.md, packages/next-sanity/src/experimental/client-components/live.tsx, packages/next-sanity/src/experimental/constants.ts, packages/next-sanity/src/experimental/live.tsx
Bypass causes the cache to not be used anyway, no point in running a cache expiry for cache that isn't used
=> fix(experimental): just refresh in draft mode
